//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int IdTicket { get; set; }
        public int IdCustomer { get; set; }
        public string DescriptionProblem { get; set; }
        public string Solution { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool RegCanceled { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
